### ISSUE TITLE
Crash on Parent/Child ViewModel sample

### ISSUE THREAD

**Issue by tasomaniac** [airbnb/MvRx#256]
When clicked, the new `Parent/Child ViewModel` sample introduced in #247 crashes when started. 

```
2019-07-30 00:25:48.428 12551-12551/com.airbnb.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.sample, PID: 12551
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:293)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:333)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:138)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:124)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2420)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2466)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2416)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2372)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalAccessError: Field 'com.airbnb.mvrx.MvRxExtensionsKt.$$delegatedProperties' is inaccessible to class 'com.airbnb.mvrx.sample.features.parentfragment.ChildFragment$$special$$inlined$parentFragmentViewModel$1' (declaration of 'com.airbnb.mvrx.sample.features.parentfragment.ChildFragment$$special$$inlined$parentFragmentViewModel$1' appears in /data/app/com.airbnb.sample-0JWsg0OQBS4zHquwgh_SIw==/base.apk!classes5.dex)
        at com.airbnb.mvrx.sample.features.parentfragment.ChildFragment$$special$$inlined$parentFragmentViewModel$1.invoke(MvRxExtensions.kt:42)
        at com.airbnb.mvrx.sample.features.parentfragment.ChildFragment$$special$$inlined$parentFragmentViewModel$1.invoke(Unknown Source:0)
        at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:53)
        at com.airbnb.mvrx.lifecycleAwareLazy$1.onStart(lifecycleAwareLazy.kt:31)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:215)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:293) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:333) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:138) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:124) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2420) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418) 
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195) 
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078) 
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2466) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483) 
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2646) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2416) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2372) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by corjohnson** [comment]
I can repro this as well

**Comment by rossbacher** [comment]
I had a look at this. It looks like a compiler bug, maybe updating Kotlin will help, if not we should report this.

What happens is the following:

The compiler, when compiling `MvRxExtensionKt` creates a `static final` field like this:

 ```java
static final /* synthetic */ KProperty[] $$delegatedProperties = {Reflection.property0(new PropertyReference0Impl(Reflection.getOrCreateKotlinPackage(MvRxExtensionsKt.class, "mvrx_debug"), "notFoundMessage", "<v#0>"))};
```

in the class `com.airbnb.mvrx.MvRxExtensionsKt`

and when compiling `ParentFragment` it creates this line in the `invoke` method of a Lambda:

```java
final KProperty kProperty = MvRxExtensionsKt.$$delegatedProperties[0];
```

accessing the field in `MvRxExtensionsKt`. However this is in the package `com.airbnb.mvrx.sample.features.parentfragment` thus it is not allowed.

**Comment by rossbacher** [comment]
I tested updating Kotlin to 1.3.41 and the same bug still exists. I'll open an issue with Jetbrains about this tomorrow.

**Comment by rossbacher** [comment]
PR was merged, this should fix the issue.

**Comment by rossbacher** [comment]
Sorry wrong issue...

**Comment by rossbacher** [comment]
See: https://youtrack.jetbrains.com/issue/KT-33423

**Comment by yrickwong** [comment]
> Looks like the issue is fixed in Kotlin 1.3.50.
I tested Upgrade Kotlin to 1.3.50, AGP to 3.5.0, and Gradle to 5.6 
but still exists
